# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fs_msgs/SlamState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SlamState(genpy.Message):
  _md5sum = "a77c00628d1b607092740dc262c21142"
  _type = "fs_msgs/SlamState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#
# Give the lap count and number of cones
#

uint8 lap_counter
int32 cones_count_actual
int32 cones_count_all
"""
  __slots__ = ['lap_counter','cones_count_actual','cones_count_all']
  _slot_types = ['uint8','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lap_counter,cones_count_actual,cones_count_all

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SlamState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lap_counter is None:
        self.lap_counter = 0
      if self.cones_count_actual is None:
        self.cones_count_actual = 0
      if self.cones_count_all is None:
        self.cones_count_all = 0
    else:
      self.lap_counter = 0
      self.cones_count_actual = 0
      self.cones_count_all = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2i().pack(_x.lap_counter, _x.cones_count_actual, _x.cones_count_all))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.lap_counter, _x.cones_count_actual, _x.cones_count_all,) = _get_struct_B2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2i().pack(_x.lap_counter, _x.cones_count_actual, _x.cones_count_all))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.lap_counter, _x.cones_count_actual, _x.cones_count_all,) = _get_struct_B2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2i = None
def _get_struct_B2i():
    global _struct_B2i
    if _struct_B2i is None:
        _struct_B2i = struct.Struct("<B2i")
    return _struct_B2i
