(cl:in-package fs_msgs-msg)
(cl:export '(COMPUTATION_MODE-VAL
          COMPUTATION_MODE
          ATTITUDE_VALID-VAL
          ATTITUDE_VALID
          HEADING_VALID-VAL
          HEADING_VALID
          VELOCITY_VALID-VAL
          VELOCITY_VALID
          POSITION_VALID-VAL
          POSITION_VALID
          VERT_REF_USED-VAL
          VERT_REF_USED
          MAG_REF_USED-VAL
          MAG_REF_USED
          GPS1_VEL_USED-VAL
          GPS1_VEL_USED
          GPS1_POS_USED-VAL
          GPS1_POS_USED
          GPS1_HDT_USED-VAL
          GPS1_HDT_USED
          GPS2_VEL_USED-VAL
          GPS2_VEL_USED
          GPS2_POS_USED-VAL
          GPS2_POS_USED
          GPS2_HDT_USED-VAL
          GPS2_HDT_USED
          ODO_USED-VAL
          ODO_USED
          DVL_BT_USED-VAL
          DVL_BT_USED
          DVL_WT_USED-VAL
          DVL_WT_USED
          USBL_USED-VAL
          USBL_USED
          AIR_DATA_USED-VAL
          AIR_DATA_USED
          ZUPT_USED-VAL
          ZUPT_USED
          ALIGN_VALID-VAL
          ALIGN_VALID
          DEPTH_USED-VAL
          DEPTH_USED
))