(cl:defpackage fs_msgs-msg
  (:use )
  (:export
   "<CLASSIFIEDBOUNDINGBOX>"
   "CLASSIFIEDBOUNDINGBOX"
   "<CLASSIFIEDBOUNDINGBOXES>"
   "CLASSIFIEDBOUNDINGBOXES"
   "<CONE>"
   "CONE"
   "<CONESTATS>"
   "CONESTATS"
   "<CONEWITHSTATS>"
   "CONEWITHSTATS"
   "<CONES>"
   "CONES"
   "<CONESWITHSTATS>"
   "CONESWITHSTATS"
   "<CONTROLLEROUTPUT>"
   "CONTROLLEROUTPUT"
   "<PIDCONTROLLED>"
   "PIDCONTROLLED"
   "<SBG_EKF_STATUS>"
   "SBG_EKF_STATUS"
   "<SLAMSTATE>"
   "SLAMSTATE"
   "<WHEELSPEEDS>"
   "WHEELSPEEDS"
  ))

