
(cl:in-package :asdf)

(defsystem "fs_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "ClassifiedBoundingBox" :depends-on ("_package_ClassifiedBoundingBox"))
    (:file "_package_ClassifiedBoundingBox" :depends-on ("_package"))
    (:file "ClassifiedBoundingBoxes" :depends-on ("_package_ClassifiedBoundingBoxes"))
    (:file "_package_ClassifiedBoundingBoxes" :depends-on ("_package"))
    (:file "Cone" :depends-on ("_package_Cone"))
    (:file "_package_Cone" :depends-on ("_package"))
    (:file "ConeStats" :depends-on ("_package_ConeStats"))
    (:file "_package_ConeStats" :depends-on ("_package"))
    (:file "ConeWithStats" :depends-on ("_package_ConeWithStats"))
    (:file "_package_ConeWithStats" :depends-on ("_package"))
    (:file "Cones" :depends-on ("_package_Cones"))
    (:file "_package_Cones" :depends-on ("_package"))
    (:file "ConesWithStats" :depends-on ("_package_ConesWithStats"))
    (:file "_package_ConesWithStats" :depends-on ("_package"))
    (:file "ControllerOutput" :depends-on ("_package_ControllerOutput"))
    (:file "_package_ControllerOutput" :depends-on ("_package"))
    (:file "PIDControlled" :depends-on ("_package_PIDControlled"))
    (:file "_package_PIDControlled" :depends-on ("_package"))
    (:file "Sbg_ekf_status" :depends-on ("_package_Sbg_ekf_status"))
    (:file "_package_Sbg_ekf_status" :depends-on ("_package"))
    (:file "SlamState" :depends-on ("_package_SlamState"))
    (:file "_package_SlamState" :depends-on ("_package"))
    (:file "Wheelspeeds" :depends-on ("_package_Wheelspeeds"))
    (:file "_package_Wheelspeeds" :depends-on ("_package"))
  ))