// Generated by gencpp from file fs_msgs/Cones.msg
// DO NOT EDIT!


#ifndef FS_MSGS_MESSAGE_CONES_H
#define FS_MSGS_MESSAGE_CONES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <fs_msgs/Cone.h>

namespace fs_msgs
{
template <class ContainerAllocator>
struct Cones_
{
  typedef Cones_<ContainerAllocator> Type;

  Cones_()
    : header()
    , cones()  {
    }
  Cones_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cones(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::fs_msgs::Cone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fs_msgs::Cone_<ContainerAllocator> >::other >  _cones_type;
  _cones_type cones;





  typedef boost::shared_ptr< ::fs_msgs::Cones_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fs_msgs::Cones_<ContainerAllocator> const> ConstPtr;

}; // struct Cones_

typedef ::fs_msgs::Cones_<std::allocator<void> > Cones;

typedef boost::shared_ptr< ::fs_msgs::Cones > ConesPtr;
typedef boost::shared_ptr< ::fs_msgs::Cones const> ConesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fs_msgs::Cones_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fs_msgs::Cones_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fs_msgs::Cones_<ContainerAllocator1> & lhs, const ::fs_msgs::Cones_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cones == rhs.cones;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fs_msgs::Cones_<ContainerAllocator1> & lhs, const ::fs_msgs::Cones_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::Cones_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::Cones_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::Cones_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::Cones_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::Cones_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::Cones_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fs_msgs::Cones_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1c021b091fd72e734d7120dfc8ab7c2";
  }

  static const char* value(const ::fs_msgs::Cones_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1c021b091fd72e7ULL;
  static const uint64_t static_value2 = 0x34d7120dfc8ab7c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::fs_msgs::Cones_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fs_msgs/Cones";
  }

  static const char* value(const ::fs_msgs::Cones_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fs_msgs::Cones_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Array of cones\n"
"#\n"
"\n"
"# Extra information on the message\n"
"# header.stamp: time of the message\n"
"# header.frame_id: frame in which the cones are given\n"
"Header header\n"
"\n"
"# Array of cones\n"
"Cone[] cones\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: fs_msgs/Cone\n"
"#\n"
"# Description of a cone\n"
"#\n"
"\n"
"# 2D-position of the cone\n"
"float64 x\n"
"float64 y\n"
"\n"
"# Color of the cone\n"
"uint8 UNDEFINED = 0\n"
"uint8 YELLOW = 1\n"
"uint8 BLUE = 2\n"
"uint8 SMALL_ORANGE = 3\n"
"uint8 BIG_ORANGE = 4\n"
"\n"
"uint8 color\n"
"\n"
"# Covariance on the position [m^2] (2x2 matrix in row-major order)\n"
"float64[4] covariance\n"
"\n"
"# Confidence in the detection\n"
"float64 probability\n"
;
  }

  static const char* value(const ::fs_msgs::Cones_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fs_msgs::Cones_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cones_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fs_msgs::Cones_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fs_msgs::Cones_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cones[]" << std::endl;
    for (size_t i = 0; i < v.cones.size(); ++i)
    {
      s << indent << "  cones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fs_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FS_MSGS_MESSAGE_CONES_H
