// Generated by gencpp from file fs_msgs/ControllerOutput.msg
// DO NOT EDIT!


#ifndef FS_MSGS_MESSAGE_CONTROLLEROUTPUT_H
#define FS_MSGS_MESSAGE_CONTROLLEROUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fs_msgs
{
template <class ContainerAllocator>
struct ControllerOutput_
{
  typedef ControllerOutput_<ContainerAllocator> Type;

  ControllerOutput_()
    : header()
    , steering(0.0)
    , torque(0.0)
    , velocity(0.0)  {
    }
  ControllerOutput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering(0.0)
    , torque(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _torque_type;
  _torque_type torque;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::fs_msgs::ControllerOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fs_msgs::ControllerOutput_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerOutput_

typedef ::fs_msgs::ControllerOutput_<std::allocator<void> > ControllerOutput;

typedef boost::shared_ptr< ::fs_msgs::ControllerOutput > ControllerOutputPtr;
typedef boost::shared_ptr< ::fs_msgs::ControllerOutput const> ControllerOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fs_msgs::ControllerOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fs_msgs::ControllerOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fs_msgs::ControllerOutput_<ContainerAllocator1> & lhs, const ::fs_msgs::ControllerOutput_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steering == rhs.steering &&
    lhs.torque == rhs.torque &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fs_msgs::ControllerOutput_<ContainerAllocator1> & lhs, const ::fs_msgs::ControllerOutput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fs_msgs::ControllerOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fs_msgs::ControllerOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fs_msgs::ControllerOutput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54e8a5e2d902d5c9c3fb89ad8e3f99e8";
  }

  static const char* value(const ::fs_msgs::ControllerOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54e8a5e2d902d5c9ULL;
  static const uint64_t static_value2 = 0xc3fb89ad8e3f99e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fs_msgs/ControllerOutput";
  }

  static const char* value(const ::fs_msgs::ControllerOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 steering\n"
"float64 torque\n"
"float64 velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fs_msgs::ControllerOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering);
      stream.next(m.torque);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fs_msgs::ControllerOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fs_msgs::ControllerOutput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "torque: ";
    Printer<double>::stream(s, indent + "  ", v.torque);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FS_MSGS_MESSAGE_CONTROLLEROUTPUT_H
